### ISSUE TITLE
"No connections" illustration

### ISSUE THREAD

**Issue by richardolsson** [zetkin/www.zetk.in#145]
Add an illustration to the message that is displayed on "My page" when user is not connected to any organizations.

**Comment by richardolsson** [comment]
Screenshot for context.

![1_not-connected](https://user-images.githubusercontent.com/550212/31385510-cb7f16e4-adc3-11e7-9f5e-ea33a657ccf7.png)

**Comment by rebeccatencic** [comment]
![no-connection1](https://user-images.githubusercontent.com/26344452/33661926-2eb11aa8-da8a-11e7-9489-2ab7986b77b2.png)

This is what the illustration looks like right now. Do I need to make any changes before we can consider it finished?

**Comment by richardolsson** [comment]
I think this looks great! My only concern is that the perspective seems _a little bit_ off on that second group from the left (the blue, mid-distance one). Move up a little bit, or make it smaller? Does that make sense?

**Comment by richardolsson** [comment]
Changed my mind! Please attach (or e-mail) the illustrator file, and lets close this. :)

![dance](https://media.giphy.com/media/TLqkzhMIZxAQg/giphy.gif)

**Comment by richardolsson** [comment]
Actually, reopening and reassigning to myself because the illustration needs to be integrated into the actual website.
