### ISSUE TITLE
Dev scripts for Windows

### ISSUE THREAD

**Issue by richardolsson** [zetkin/www.zetk.in#147]
Add developer scripts for Windows similar to those introduced by zetkin/organize.zetk.in#639.

**Comment by olleolleolle** [comment]
I believe this is fixed in #168.

**Comment by richardolsson** [comment]
I think you're right @olleolleolle! Thanks for looking it up.

However, as I look closer I realize that both the windows scripts introduced in #168 and the current version of the bash scripts used on OSX and Linux are out of date. The following needs to happen, and maybe you could help?

* Update `ZETKIN_APP_ID` and `ZETKIN_APP_KEY` in the windows run script to the same values that are in the bash scripts
* Add `TOKEN_SECRET` to both scripts. The value can be any 24 character string, e.g. `012345678901234567890123`
