### ISSUE TITLE
Rethink dashboard

### ISSUE THREAD

**Issue by richardolsson** [zetkin/www.zetk.in#170]
We have outgrown the dashboard ("My page") and need to rethink it's layout. Currently only campaigns, bookings and assignments are shown on the dashboard. It would be good to be able to show (or easily link to):

* Campaigns (including the organization running the campaign, see #169)
* Booked actions (including the location, campaign and organization)
* Unbooked sign-ups (see #101)
* Call assignments (including the organization)
* Canvass assignments (including the organization)
* Groups managed by you (including the organization they belong to)
* Surveys (including the organization they belong to)
* Organizations (those you're connected to, and others which may be relevant to you, with links to organization pages)
* Alerts and important messages, e.g. changes to terms or recommendations to complete your profile

Things to take into consideration:

* Interface could be modular (e.g. like the new Group page) because not all users will have all of the above sections.
* Maybe clarify which sections are _not_ visible, e.g. using simple text such as "You don't have any call assignments, canvass assignments or groups that you manage". This way a user looking for something (e.g. a call assignment) can know that they're looking in the right place – it just doesn't exist.
* Needs to work on desktop and mobile, with/without javascript

In the process of fixing this, related issues #102, #136 and #159 should also be fixed.

**Comment by richardolsson** [comment]
Let's have a quick chat about this next week, @jensborje. You have two weeks scheduled during this next sprint, and my intent is to let you spend most of that time designing and implementing the new dashboard. Hopefully you think that sounds like a good idea. :)

**Comment by jensborje** [comment]
Sketches and prototype here: https://sketch.cloud/s/APzO4
