### ISSUE TITLE
Dedicated phone widget

### ISSUE THREAD

**Issue by richardolsson** [zetkin/www.zetk.in#260]
Create (or reuse) a mobile phone number widget with country code support to be used in the registration form.

**Comment by richardolsson** [comment]
We have had a large number of users contacting us recently with registration issues which turn out to be caused by our current solution confusing them.

**Comment by richardolsson** [comment]
Could you take a look at this @niklasva82 and we can try to get it out with this next release that has been held up?

**Comment by niklasva82** [comment]
Something like this one?
![phonefield](https://user-images.githubusercontent.com/14962107/93208819-78449080-f75d-11ea-8957-ab2542129ba1.gif)

**Comment by richardolsson** [comment]
Yeah, something like that! Ideally one that blends in well with the rest of the form.

I also like being able to type the entire number, without having to select a country using the mouse. Some like to type, others like to select. :)

**Comment by niklasva82** [comment]
:+1: also ideally being able to type more than one character in the select field to find the country. So annoying :P
