### ISSUE TITLE
Handle actions without acitivty/title and location

### ISSUE THREAD

**Issue by niklasva82** [zetkin/www.zetk.in#298]
Now that activities can be null, hide any activities that do not have a title or activity.

**Comment by richardolsson** [comment]
Not sure how to interpret this issue, so I might just be repeating something that you've already thought about, but here are my thoughts:

* Actions without a location should have the label "No physical location" where the name of the location was previously
* Actions without title or activity should have the label "Untitled event", localized to the user's language
* There might need to be changes made to the clustering logic

I believe these issues are actually in `zetkin-common`, and affect both www and Call.
