### ISSUE TITLE
My Pages – Content breakdown 

### ISSUE THREAD

**Issue by jensborje** [zetkin/www.zetk.in#3]
My pages
- User element
  - Avatar image
  - Name
  - Settings link
- Upcoming bookings
  - Incomplete Survey responses
  - Incomplete Meetup registrations
  - Your upcoming Action bookings
  - Your upcoming Meetup bookings
  - Your upcoming Call assignments
- Upcoming in your Organizations
  - Specific organisation
    - Open surveys
    - Meetups
    - Campaigns
- Upcoming close to you
  - Specific organisation
    - Open surveys
    - Meetups
    - Campaigns

**Comment by richardolsson** [comment]
This has been implemented.
