### ISSUE TITLE
Warning when not connected to organization

### ISSUE THREAD

**Issue by richardolsson** [zetkin/www.zetk.in#80]
When a user first registers, if they did not arrive using a join-link, their dashboard will be completely empty. Add some sort of warning describing that the reason behind this is that they're not connected to any organizations and that they may try to find their organization (via connect-links on their home page, #40 or #79) and connect to it.

**Comment by jensborje** [comment]
Anything else needed?

![skarmavbild 2017-02-09 kl 16 13 39](https://cloud.githubusercontent.com/assets/1271517/22789261/bf6a56f2-eee2-11e6-8b84-6a614aec760a.png)
