### ISSUE TITLE
Registration error difficult to read

### ISSUE THREAD

**Issue by richardolsson** [zetkin/www.zetk.in#84]
The error label after trying to register an account that already exists is grey on greyish background, making it incredibly difficult to read or even spot.

![image](https://cloud.githubusercontent.com/assets/550212/22775859/bd0c6d76-eead-11e6-8226-7baedaca1ae0.png)

**Comment by jensborje** [comment]
Better?

![skarmavbild 2017-02-09 kl 14 24 58](https://cloud.githubusercontent.com/assets/1271517/22785192/9d21e556-eed3-11e6-8a32-c06059c4f61a.png)
