### ISSUE TITLE
Unsecure connection 

### ISSUE THREAD

**Issue by jensborje** [zetkin/www.zetk.in#85]
When entering the URL as zetk.in without www, the browser sometimes return as unsecure connection.

<img width="1552" alt="skarmavbild 2017-02-09 kl 13 21 17" src="https://cloud.githubusercontent.com/assets/1271517/22783182/f6cf4f98-eeca-11e6-964e-bff086cbc96b.png">

**Comment by richardolsson** [comment]
This is due to the certificate not including the domain without sub-domains. I've created an issue for this in the server configuration repository.
